### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by pekq** [hilkeheremans/redux-persist-seamless-immutable#1]
Hi, thanks for you efforts!
However, I'm having problems compiling this.

```
./node_modules/redux-persist-seamless-immutable/src/reconciler.js
Module parse failed: Unexpected token (9:19)
You may need an appropriate loader to handle this file type.

|   { debug, mergeDeep = false }
| ) => {
|   let newState = { ...reducedState };
|   // only rehydrate if inboundState exists and is an object
|   if (inboundState && typeof inboundState === 'object') {
```  

My project uses [create-react-app](https://github.com/facebookincubator/create-react-app).  
Node: `v8.8.0`

**Comment by hilkeheremans** [comment]
Ah! I'll take a look. ~Give me a few hours as I have a few other things to tend to.~
 
EDIT: OK, pretty easy to fix -- forgot this baby was using object rest spread and that it doesn't get transpiled when added as a dep. I tested this mainly on React Native where this was not an issue.

I'll add some transpilation stuff in a moment.

**Comment by hilkeheremans** [comment]
There you go, see `v1.0.1`.

Enjoy!
